language: python
matrix:
    include:
        - os: linux
          python: 2.7
          dist: precise
          name: Python 2 on Ubuntu 12
        - os: linux
          python: 3.6
          dist: precise
          name: Python 3 on Ubuntu 12
        - os: linux
          python: nightly
          dist: precise
          name: Latest Python on Ubuntu 12
        - os: linux
          python: 2.7
          dist: trusty
          # FFMPEG workarounds for Ubuntu 14
          before_install:
            - sudo add-apt-repository -y ppa:mc3man/trusty-media
            - sudo apt-get update
            - sudo apt-get install -y ffmpeg
          name: Python 2 on Ubuntu 14
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y ffmpeg; fi
script: "nosetests"
notifications:
email: false
