language: python
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.6
        - os: linux
          python: nightly
        - os: osx
          language: generic
          env: PYTHON=python
        - os: osx
          language: generic
          env: PYTHON=python3
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p $PYTHON; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
script: "nosetests"
notifications:
email: false
